### ISSUE TITLE
Serializing UnityEngine.AnimationCurve Doesn't Yield Class's Fields/Properties

### ISSUE THREAD

**Issue by AquaGeneral** [pbhogan/TinyJSON#6]
When serializing an AnimationCurve, none of its fields/properties are saved. Instead this is the only result:

    "animationCurve":{  
        "@type":"UnityEngine.AnimationCurve"
    },

Any idea why this is occurring? I notice that the UnityEngine.Color is serialized correctly.

**Comment by pbhogan** [comment]
Because it has no public fields, only properties. TinyJSON does not serialized properties unless they are annotated with the Include attribute. This is the correct behavior because 99% of the time you don't want to serialize properties since they tend to be computed values or have some get/set logic associated. Unity (and I believe .NET) serialization works the same way (requiring the Serializable attribute).

UnityEngine.Color stores its values in public fields, so it works "out of the box".

Since you can't modify the AnimationCurve code I don't see a way around this, and TinyJSON currently doesn't have a feature for adding custom object serializers.

In general, it's not going to work well with Unity's types because they are often thin wrappers around native C++ objects and Unity handles all the serialization internally. Unfortunately, they aren't nice clean C# objects with the exception of some of the very basic types (Color, Vector2, Vector3). Arguably AnimationCurve should be simple, but I guess Unity didn't think so... probably for optimization purposes.

**Comment by AquaGeneral** [comment]
Thanks for the response (and the crazy speed of it!). That all makes sense. For what I'm doing I could just make a "faux" AnimationCurve that stores the data I want.

**Comment by pbhogan** [comment]
It's worth mentioning you could actually use BeforeEncode and AfterDecode hooks to manually stuff it into the encoded proxy objects, but if you can get away with your own simple custom object that would be much simpler and probably less prone to breakage if Unity messes with their internals.
